# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /Volumes/Elements/mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ernies
      MONGO_INITDB_ROOT_PASSWORD: mko09IJNbhu8

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ernies
      ME_CONFIG_MONGODB_ADMINPASSWORD: mko09IJNbhu8
      ME_CONFIG_MONGODB_URL: mongodb://ernies:mko09IJNbhu8@mongo:27017/

  metrics-api:
    image: ernea5956/metrics-api:1.0.0
    restart: always
    ports:
      - 3000:3000
    environment:
      MONGO_URI: mongodb://ernies:mko09IJNbhu8@mongo:27017
      MONGO_DB_NAME: metrics
      ALGORITHM: aes-256-cbc
      SALT: a77baf9a8ec280a7f9329e74f41a75e5
      SECURITY_KEY: a77baf9a8ec280a7f9329e74f41a75e5
      JWT_SECRET: NotANewKeyButAnOldOne

  metrics:
    image: ernea5956/metrics:1.0.6
    restart: always
    ports:
      - 8080:8080